default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: trackfund_development

test:
  <<: *default
  database: trackfund_test

production:
  <<: *default
  database: trackfund_production
  username: trackfund
  password: <%= ENV["TRACKFUND_DB_PASSWORD"] %>
